import React from "react";
import { nanoid } from "nanoid";
import housesForSale from "./data/housesForSale";
import HouseCard from "./components/HouseCard";

export default function App() {
  /* Challenge

    The JSX of the houseCards being generated by the map method below needs to be put in a separate functional component. Your task is to do so as follows:
    
            
		
	
		   
		4. The HouseCard component should be placed in a separate file in the components folder and 
           imported into this App.tsx file.
        
        5. You should only pass up to a maximum of four props being into <HouseCard />. You 
           *should not* manually pass every piece of houseData as a seperate prop! The site should look and behave exactly the same once you've completed these tasks. The challenge here is just about improving the code "underneath the hood"!
*/
  const houseData = housesForSale;

  return (
    <div className="wrapper">
      <header>
        <img className="logo" src="images/logo.png" />
      </header>
      <div className="house-cards-container">
        {houseData.map((house, index, array) => (
          <HouseCard key={house.id} index={index} array={array} houseData={house} />
        ))}
      </div>
    </div>
  );
}
